FROM python:latest
USER root

RUN apt-get update
RUN apt-get install fonts-noto-cjk fonts-noto-hinted

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

#pip install
RUN pip install gym
RUN pip install register
RUN pip install pymongo
RUN pip install numpy
RUN pip install pandas